title: Optionals as query params values
given:
  - time: 2014-12-24T17:01:21.795+02:00
wts:
  - when: |
       GET params/query/withOptionalString?a=1&b=2
    then: |
       a=1 b=2
  - when: |
       GET params/query/withOptionalString?a=1
    then: |
       a=1 b=default
  - when: |
       GET params/query/withOptionalDate?a=2014-10-08T10:11:12%2B0200&b=2014-10-09T10:11:12%2B0200
    then: |
       a=2014-10-08T08:11:12.000Z b=2014-10-09T08:11:12.000Z
  - when: |
       GET params/query/withOptionalDate?a=2014-10-08T10:11:12%2B0200
    then: |
       a=2014-10-08T08:11:12.000Z b=1970-01-01T00:00:00.000Z
